### ISSUE TITLE
meaning of output

### ISSUE THREAD

**Issue by NicolaDM** [ihh/trajectory-likelihood#1]
Thank you very much for this!
May I ask information regarding the interpretation of the output?
For example, with the command
./trajeclike --gamma 0.999999 --mu 4.0 -r 0.75 -t 0.001 -E 3 -L 5
I get the output
0.998002 0.000249339 0.000186896 0.000140093 0.000104995 7.87331e-05
0.000249339 1.48066e-07 9.62265e-08 5.24737e-08 1.31658e-08 9.87325e-09
0.000186896 9.62266e-08 5.24611e-08 1.31544e-08 9.85677e-09 7.39174e-09
0.000140093 5.24738e-08 1.31544e-08 9.85308e-09 7.38305e-09 5.53666e-09
0.000104995 1.31659e-08 9.85679e-09 7.38306e-09 5.53222e-09 4.1487e-09
7.87335e-05 9.87329e-09 7.39176e-09 5.53667e-09 4.1487e-09 3.11118e-09

My interpretation is that this is a matrix 6x6 where entry in row i and column j represents the probability that a chop zone has i-1 insertion columns and j-1 deletion columns. Is this correct, or are insertions and deletions along the columns and rows respectively instead? It doesn't matter much since I am trying to enforce almost equally distributed insertions and deletions, but I just wanted to make sure.

My other question is about the -E and -L options. In the Miklos, Lunter and Holmes 2004 paper, the maximum number of events is set to 3 and the maximum indel length to 100. Does this corresponds to using options -E 3 -L 100 here? And if not, what options would be reasonable instead? It seems to me that running time increases exponentially with the option -L, and values of -L above about 30 do not seem feasible for my applications (for which I need to run this script many times).

Thanks again and best wishes!

**Comment by NicolaDM** [comment]
Sorry, a couple of additional issues:
For high divergence, the probabilities do not seem to sum up to one, for example if I use
trajeclike --gamma 0.999999 --mu 4.0 -r 0.75 -t 1.0 -E 3 -L 10 
How should I interpret these? Should I normalize the values by the sum of all the probabilities in the output?

When running with the -s option, I see that the output values are also represented as frequency rather than counts - how should I interpret these, in particular, how do I know the number of chop zones in the simulated alignment?

A last thing I noticed is that simulating with the -s option, for example
trajeclike --gamma 0.999999 --mu 4.0 -r 0.75 -t 1.0 -E 3 -L 10 -s -i 2000000 -n 1
Takes a long time, particular when -t is high, for example -t 1.0 . Are the chop zones simulated not by just sampling from the chop zone probabilities (which should take more or less the same CPU time independently of -t) ?

**Comment by ihh** [comment]
Hi @NicolaDM 

- yes the entry in row i, column j is the probability of deleting i residues and inserting j residues before the next match. This information on how to interpret the numbers is also printed if you specify verbose output with `-v1` (or a higher number e.g. `-v2`, `-v3` etc. which will also display more progress information on standard error)
- yes `-E` is the max number of events and `-L` the max number of inserted/deleted residues in any single event (it also plays a dual role as the maximum length of any chop zone; this is not too unreasonable for this approach, since most of the probability mass comes from single-event trajectories in most cases)
- correct, runtime increases pretty dramatically with `-L`, because it needs to calculate L^2 different probabilities and the longest of those have something like L^E consistent trajectories. A strong motivator for your approach :-)
- correct, for high divergences the probabilities do not add up to one, because the chop zones of length >L are not being counted, but those longer gaps have substantial probability when the divergence time is high. You can see this even at low divergence if you set `-L` very low.
- how one deals with that is a matter of choice, I think; one could normalize as you suggest, or one could conceivably fit a simple distribution to the lower-L data (e.g. a mixture of geometrics) and thus extrapolate to higher L. The trajectory likelihood calculation is giving the exact result (at least for trajectories up to E events and L residues per indel), so it may be useful to see how much of the probability is unaccounted for
- good point, I added in an option to report the raw counts in the latest commit (68773d0). This option also reports (as the final count) the number of simulated chop zones that exceeded the length limit. As before this guide to interpretation is displayed if you turn on verbose logging with `-v1`
- no, the simulation doesn't use chop zones, it directly simulates the continuous-time Markov process (by sampling exponential waiting times until the next event, then sampling the type of event). So in general longer simulation times `-t` will mean longer runtimes as well.

**Comment by NicolaDM** [comment]
Thank you very much for the explanations!!!

I started plotting some results, but they look a bit strange so far. The most noticeable thing to me seems to me that non-empty chop zones, while getting more frequent when increasing the t divergence value, do not necessarily seem to get longer, unlike the other models I considered so far. For example, Here are the first three probabilities with a divergence of 0.01:

trajeclike --gamma 0.999999 --mu 4.0 -r 0.75 -t 0.01 -E 3 -L 20
0.980206 0.00243651 0.00181918

the ratio of the third and second number is about 0.75, as one would expect;
however, with a divergence of 0.3:

trajeclike --gamma 0.999999 --mu 4.0 -r 0.75 -t 0.3 -E 3 -L 20
0.551649 0.0342324 0.0227133

so the ratio of the third and second number is now about 0.66, which is less than before, while in reality one would expect it to become larger as t increases and chop zones tend to become larger.
Do you know if this is some misunderstanding from my part? I tried increasing -L, and using the simulation option, but the result seems to remain the same, that is, more generally, non-empty chop zones seem to get larger up until about t=0.05, then they start slowly decreasing in average length.

**Comment by ihh** [comment]
Interesting. I'm guessing this is due to the limitations of the approach: undercalculating the true mean length either due to truncating the chop zone length, and/or due to truncating the number of events that occur on a trajectory. For example, with the parameters from your example, the mean nonempty insertion length starts decreasing around t=0.055, but if I decrease the chop zone length to 15, then the decrease occurs around t=0.043, as this example shows

~~~~
perl -e '$last_eins=0;for($t=.01;$t<=.1;$t+=.001){@out=`./trajeclike --gamma 0.999999 --mu 4.0 -r 0.75 -t $t -E 3 -L 15`;$i=0;$eins=$edel=0;@p=();$ptot=0;for$_(@out){my@f=split;push@p,\@f;for$j(0..$#f){$p=$f[$j];$ptot+=$p;$eins+=$p*$j;$edel+=$p*$i}++$i}$eins/=1-$p[0]->[0];$edel/=1-$p[0]->[0];$pMissing=1-$ptot;print"t=$t E[nIns|gap]=$eins E[nDel|gap]=$edel MissingProb=$pMissing",($eins<$last_eins?" MEAN INSERTION LENGTH DECREASED":""),"\n";$last_eins=$eins}'
~~~~

The -E parameter could also be a factor, i.e. it could also be an issue that this approach does not include trajectories of >3 events. Indeed when I repeat this with simulations (which don't limit E, but do limit L) I don't see the probability dip until the time gets quite a bit larger, suggesting that both E and L are causing the mean length to be underestimated but (at least in this case) E is having a stronger effect:

~~~~
perl -e '$last_eins=0;for($t=.1;$t<=1;$t+=.1){@out=`./trajeclike -n 10000 -s --gamma 0.999999 --mu 4.0 -r 0.75 -t $t -E 3 -L 20`;$i=0;$eins=$edel=0;@p=();$ptot=0;pop@out;for$_(@out){my@f=split;push@p,\@f;for$j(0..$#f){$p=$f[$j];$ptot+=$p;$eins+=$p*$j;$edel+=$p*$i}++$i}$eins/=1-$p[0]->[0];$edel/=1-$p[0]->[0];$pMissing=1-$ptot;print"t=$t E[nIns|gap]=$eins E[nDel|gap]=$edel MissingProb=$pMissing",($eins<$last_eins?" MEAN INSERTION LENGTH DECREASED":""),"\n";$last_eins=$eins}'
~~~~

**Comment by ihh** [comment]
I have to say, I think this is pretty persuasive evidence for the need for the sort of approach you've described! It's accurate enough for very short times, but at some point there will be more than 3 events on a branch, and then this approach becomes very slow. At that point, approximating the gap distribution as a product of independent geometrics using a separation-of-variables approach, and solving numerically, seems like a reasonable approach.

**Comment by NicolaDM** [comment]
Thank you very much for checking and for providing such a great resource!
